
pid file = /run/rsyncd.pid
log file = /var/log/rsyncd.log
use chroot = yes
read only = yes
list = yes

max connections = 12
timeout = 600

uid = nobody
gid = nobody

[gentoo-zh]
    path = /srv/pub
    comment = gentoo-zh overlay distfiles and binary packages
    exclude = lost+found
    refuse options = checksum delete delete-before delete-during delete-after delete-excluded
    dont compress = *.gpkg.tar *.tar.zst *.tar.xz *.tar.gz *.zst *.xz *.gz *.bz2 *.7z *.zip *.deb *.rpm *.AppImage *.crate *.nupkg *.tgz *.whl *.vsix *.jar *.ttf *.otf
