CFLAGS="-O2 -pipe -march=x86-64 -mtune=generic"
CXXFLAGS="${CFLAGS}"
CPU_FLAGS_X86="mmx sse sse2"
MAKEOPTS="-j16 -l16"

ACCEPT_KEYWORDS="~amd64"
ACCEPT_LICENSE="-* @BINARY-REDISTRIBUTABLE"
ACCEPT_RESTRICT="* -bindist"
USE="bindist"

FEATURES="buildpkg getbinpkg binpkg-multi-instance parallel-fetch -network-sandbox -news compress-index"
EMERGE_DEFAULT_OPTS="--jobs=4 --load-average=16 --quiet-build --keep-going --with-bdeps=y --usepkg"

GENTOO_MIRRORS="https://distfiles.gentoo.org https://distfiles.gentoozh.org"
PORTAGE_BINHOST_TTL="3600"
BINPKG_FORMAT="gpkg"
