
server {
	listen 80 default_server;
	listen [::]:80 default_server;
	server_name distfiles.gentoozh.org;

	include /etc/nginx/conf.d/mirror-common.inc;
}

server {
	listen 443 ssl default_server;
	listen [::]:443 ssl default_server;
	http2 on;
	listen 443 quic reuseport;
	listen [::]:443 quic reuseport;
	server_name distfiles.gentoozh.org;

	ssl_certificate     /etc/letsencrypt/live/distfiles.gentoozh.org/fullchain.pem;
	ssl_certificate_key /etc/letsencrypt/live/distfiles.gentoozh.org/privkey.pem;

	ssl_protocols TLSv1.2 TLSv1.3;
	ssl_prefer_server_ciphers off;
	ssl_session_cache shared:SSL:10m;
	ssl_session_timeout 1d;
	ssl_session_tickets off;


	include /etc/nginx/conf.d/headers-site.inc;

	include /etc/nginx/conf.d/mirror-common.inc;
}
